module.exports = {
  assets: true,
  assetsSort: "field",
  cached: true,
  children: false,
  chunks: true,
  chunkModules: false,
  chunkOrigins: false,
  chunksSort: "field",
  colors: true,
  errors: true,
  errorDetails: true,
  hash: true,
  modules: false,
  modulesSort: "field",
  publicPath: true,
  reasons: true,
  source: false,
  timings: true,
  version: true,
  warnings: true,
}

